version: '3.8'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "development"
      JWT_SECRET_KEY: "your_jwt_secret_key"
    depends_on:
      - db
    volumes:
      - ./app:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "your_database_name"
      MYSQL_USER: "your_user"
      MYSQL_PASSWORD: "your_password"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
